from decouple import config

INITIAL_SIGNATURE = config(
    "INITIAL_SIGNATURE", cast=str, default="INSECURE_DEBUG_SIGNATURE"
)

FINANCIAL_REWARDS = {
    "NEW_USER": 10,
    "PLACE_CREATION": 10,
    "REFERRED_USER": 10,
}

FINANCIAL_DESTINATIONS = {
    "NEW_USER": {"type": "NEW_USER"},
    "PLACE_CREATION": {"type": "PLACE_CREATION"},
    "PLACE_REMOVAL": {"type": "PLACE_REMOVAL"},
    "ACHIEVEMENT_REWARD": {"type": "ACHIEVEMENT_REWARD"},
    "REFERRED_USER": {"type": "REFERRED_USER"},
}
KARMA_REWARDS = {
    "PLACE_CREATION": 10,
}
