from src.apps.media.enums import FileType

MEDIA_ROOT = "media/"
UPLOAD_DIR = "uploads/"
ALLOWED_EXTENSIONS = {
    FileType.PHOTO: {
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".bmp",
        ".tiff",
        ".webp",
        ".svg",
    },
    FileType.VIDEO: {
        ".mp4",
        ".mov",
        ".webm",
        ".avi",
        ".mkv",
        ".flv",
        ".wmv",
        ".mpeg",
    },
    FileType.DOCUMENT: {
        ".doc",
        ".docx",
        ".xls",
        ".xlsx",
        ".ppt",
        ".pptx",
        ".pdf",
        ".txt",
        ".rtf",
        ".odt",
    },
    FileType.EXECUTABLE: {
        ".exe",
        ".msi",
        ".sh",
        ".bat",
        ".bin",
        ".apk",
        ".appimage",
        ".jar",
    },
    FileType.AUDIO: {
        ".mp3",
        ".wav",
        ".ogg",
        ".aiff",
        ".aac",
        ".flac",
        ".m4a",
        ".wma",
    },
    FileType.OTHER: set(),
}
MIME_TO_EXT = {
    'image/jpeg': '.jpg',
    'image/png': '.png',
    'image/gif': '.gif',
    'image/bmp': '.bmp',
    'image/tiff': '.tiff',
    'image/webp': '.webp',
    'image/svg+xml': '.svg',
    # Video
    'video/mp4': '.mp4',
    'video/quicktime': '.mov',
    'video/webm': '.webm',
    'video/avi': '.avi',
    'video/x-matroska': '.mkv',
    'video/x-flv': '.flv',
    'video/x-ms-wmv': '.wmv',
    'video/mpeg': '.mpeg',
    # Document
    'application/msword': '.doc',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': '.docx',
    'application/vnd.ms-excel': '.xls',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': '.xlsx',
    'application/vnd.ms-powerpoint': '.ppt',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': '.pptx',
    'application/pdf': '.pdf',
    'text/plain': '.txt',
    'text/rtf': '.rtf',
    'application/vnd.oasis.opendocument.text': '.odt',
    # Executable
    'application/x-msdownload': '.exe',
    'application/x-msi': '.msi',
    'application/x-sh': '.sh',
    'application/x-bat': '.bat',
    'application/octet-stream': '.bin',
    'application/vnd.android.package-archive': '.apk',
    'application/x-appimage': '.appimage',
    'application/java-archive': '.jar',
    # Audio
    'audio/mpeg': '.mp3',
    'audio/wav': '.wav',
    'audio/ogg': '.ogg',
    'audio/aiff': '.aiff',
    'audio/aac': '.aac',
    'audio/flac': '.flac',
    'audio/x-m4a': '.m4a',
    'audio/x-ms-wma': '.wma',
}
