# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the category.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "is_for_all",
                    models.BooleanField(
                        default=False,
                        help_text="Include all users in the category.",
                        verbose_name="include all",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name of the newsletter.",
                        max_length=150,
                        verbose_name="internal name",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message of the newsletter.", verbose_name="message"
                    ),
                ),
                (
                    "shown_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Time when the newsletter was shown.",
                        verbose_name="shown at",
                    ),
                ),
                (
                    "is_shown",
                    models.BooleanField(
                        default=False,
                        help_text="Newsletter is already shown.",
                        verbose_name="shown",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shown_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Time when the notification was shown.",
                        verbose_name="shown at",
                    ),
                ),
                (
                    "is_shown",
                    models.BooleanField(
                        default=False,
                        help_text="Notification is already shown.",
                        verbose_name="shown",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="", max_length=150, verbose_name="title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="", max_length=150, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="", max_length=150, null=True, verbose_name="title"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message of the notification.", verbose_name="message"
                    ),
                ),
                (
                    "message_en",
                    models.TextField(
                        help_text="Message of the notification.",
                        null=True,
                        verbose_name="message",
                    ),
                ),
                (
                    "message_uk",
                    models.TextField(
                        help_text="Message of the notification.",
                        null=True,
                        verbose_name="message",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "PERSONAL"),
                            ("GROUP", "GROUP"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        default="SYSTEM",
                        help_text="Type of the notification.",
                        verbose_name="type",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("NOTIFICATION", "NOTIFICATION"),
                            ("GIFT", "GIFT"),
                            ("WARNING", "WARNING"),
                            ("CANCEL", "CANCEL"),
                            ("CHECKED", "CHECKED"),
                            ("CLOCK", "CLOCK"),
                            ("SETTINGS", "SETTINGS"),
                        ],
                        default="NOTIFICATION",
                        help_text="Icon of the notification.",
                        verbose_name="icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifier",
            },
        ),
        migrations.CreateModel(
            name="CategoryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.category",
                        verbose_name="category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Recipients of the category.",
                through="notifier.CategoryRecipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the event.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the event should be/was triggered.",
                        null=True,
                        verbose_name="triggered at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Is the event active?",
                        verbose_name="is active",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Recipient categories.",
                        through="notifier.CategoryEvent",
                        to="notifier.category",
                        verbose_name="categories",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="categoryevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="notifier.event",
                verbose_name="event",
            ),
        ),
        migrations.CreateModel(
            name="NewsletterEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.newsletter",
                        verbose_name="newsletter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="newsletters",
            field=models.ManyToManyField(
                blank=True,
                help_text="Newsletters included to this event.",
                through="notifier.NewsletterEvent",
                to="notifier.newsletter",
                verbose_name="newsletters",
            ),
        ),
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.event",
                        verbose_name="event",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.notification",
                        verbose_name="notification",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="notifications",
            field=models.ManyToManyField(
                blank=True,
                help_text="Notifications included to this event.",
                through="notifier.NotificationEvent",
                to="notifier.notification",
                verbose_name="notifications",
            ),
        ),
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="", verbose_name="Read"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifier.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Status",
                "verbose_name_plural": "Notification Statuses",
                "unique_together": {("user", "notification")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Recipients of the notification.",
                through="notifier.NotificationStatus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
    ]
