# Generated by Django 5.1.1 on 2024-10-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "changebility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "deletebility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
            },
        ),
        migrations.CreateModel(
            name="UserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_view_permission", models.BooleanField(default=True)),
                ("has_change_permission", models.BooleanField(default=True)),
                ("has_delete_permission", models.BooleanField(default=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="permissions.objectpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Per-User Permission",
                "verbose_name_plural": "Per-User Permissions",
                "unique_together": {("user", "permission")},
            },
        ),
    ]
