# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "changebility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "deletebility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "verbose_name": "Object Permission",
                "verbose_name_plural": "Object Permissions",
            },
        ),
        migrations.CreateModel(
            name="ModelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createbility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                        help_text="Createbility level for the model.",
                        verbose_name="createbility level",
                    ),
                ),
                (
                    "visibility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                        help_text="The default visibility level for the model.",
                        verbose_name="visibility level",
                    ),
                ),
                (
                    "changebility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                        help_text="Default changebility level for the model.",
                        verbose_name="changebility level",
                    ),
                ),
                (
                    "deletebility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                        help_text="Default deletebility level for the model.",
                        verbose_name="deletebility level",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="The name of the model you would like to add permissions for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        unique=True,
                        verbose_name="model name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Permission",
                "verbose_name_plural": "Model Permissions",
            },
        ),
        migrations.CreateModel(
            name="UserModelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_create_permission", models.BooleanField(default=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="permissions.modelpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Model Permission",
                "verbose_name_plural": "User-Model Permissions",
            },
        ),
        migrations.CreateModel(
            name="UserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_view_permission", models.BooleanField(default=True)),
                ("has_change_permission", models.BooleanField(default=True)),
                ("has_delete_permission", models.BooleanField(default=True)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="permissions.objectpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User-Object Permission",
                "verbose_name_plural": "User-Object Permissions",
                "unique_together": {("user", "permission")},
            },
        ),
    ]
