# Generated by Django 5.1.1 on 2024-10-06 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "createbility_level",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "SUPERUSERS"),
                            (100, "ADMINISTRATORS"),
                            (200, "OWNERS"),
                            (300, "AUTHENTICATED"),
                            (400, "EVERYONE"),
                            (500, "BANNED"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={
                "verbose_name": "Model Permission",
                "verbose_name_plural": "Model Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="objectpermission",
            options={
                "verbose_name": "Object Permission",
                "verbose_name_plural": "Object Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="userobjectpermission",
            options={
                "verbose_name": "User-Object Permission",
                "verbose_name_plural": "User-Object Permissions",
            },
        ),
        migrations.CreateModel(
            name="UserModelPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="permissions.modelpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
