# Generated by Django 5.1.1 on 2024-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0002_modelpermission_alter_objectpermission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodelpermission",
            options={
                "verbose_name": "User-Model Permission",
                "verbose_name_plural": "User-Model Permissions",
            },
        ),
        migrations.AddField(
            model_name="modelpermission",
            name="changebility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="modelpermission",
            name="deletebility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="modelpermission",
            name="visibility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
            ),
        ),
    ]
