# Generated by Django 5.1.1 on 2024-10-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0003_alter_usermodelpermission_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelpermission",
            name="model",
            field=models.CharField(
                choices=[("blog.BlogPost", "Blog Posts")],
                default=None,
                help_text="The name of the model you would like to add permissions for.",
                verbose_name="Model Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermodelpermission",
            name="has_create_permission",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="createbility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Default createbility level for the model.",
                verbose_name="Createbility Level",
            ),
        ),
    ]
