# Generated by Django 5.1.1 on 2024-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_modelpermission_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpermission",
            name="changebility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Default changebility level for the model.",
                verbose_name="Changebility Level",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="createbility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Createbility level for the model.",
                verbose_name="Createbility Level",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="deletebility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Default deletebility level for the model.",
                verbose_name="Deletebility Level",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="model",
            field=models.CharField(
                choices=[("blog.BlogPost", "Blog Posts")],
                help_text="The name of the model you would like to add permissions for.",
                unique=True,
                verbose_name="Model Name",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="visibility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="The default visibility level for the model.",
                verbose_name="Visibility Level",
            ),
        ),
    ]
