# Generated by Django 5.1.2 on 2024-12-07 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("permissions", "0006_alter_modelpermission_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelpermission",
            name="changebility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Default changebility level for the model.",
                verbose_name="changebility level",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="createbility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Createbility level for the model.",
                verbose_name="createbility level",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="deletebility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="Default deletebility level for the model.",
                verbose_name="deletebility level",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="model",
            field=models.ForeignKey(
                help_text="The name of the model you would like to add permissions for.",
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                unique=True,
                verbose_name="model name",
            ),
        ),
        migrations.AlterField(
            model_name="modelpermission",
            name="visibility_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "SUPERUSERS"),
                    (100, "ADMINISTRATORS"),
                    (200, "OWNERS"),
                    (300, "AUTHENTICATED"),
                    (400, "EVERYONE"),
                    (500, "BANNED"),
                ],
                default=0,
                help_text="The default visibility level for the model.",
                verbose_name="visibility level",
            ),
        ),
    ]
