# Generated by Django 5.1.1 on 2024-09-24 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "show_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Planned time to show.",
                        verbose_name="Show At",
                    ),
                ),
                (
                    "is_shown",
                    models.BooleanField(
                        default=False,
                        help_text="Notification is already shown.",
                        verbose_name="Shown",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="", max_length=150, verbose_name="Title"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="", max_length=150, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="", max_length=150, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message of the notification.", verbose_name="Message"
                    ),
                ),
                (
                    "message_en",
                    models.TextField(
                        help_text="Message of the notification.",
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                (
                    "message_uk",
                    models.TextField(
                        help_text="Message of the notification.",
                        null=True,
                        verbose_name="Message",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "PERSONAL"),
                            ("GROUP", "GROUP"),
                            ("SYSTEM", "SYSTEM"),
                        ],
                        default="SYSTEM",
                        help_text="Type of the notification.",
                        verbose_name="Type",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[("NOTIFICATION", "NOTIFICATION")],
                        default="NOTIFICATION",
                        help_text="Icon of the notification.",
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="", verbose_name="Read"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Status",
                "verbose_name_plural": "Notification Statuses",
                "unique_together": {("user", "notification")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                help_text="",
                through="notifications.NotificationStatus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipients",
            ),
        ),
    ]
