# Generated by Django 5.2.8 on 2026-01-15 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the provider.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the provider.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "physical_provider",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("WEBSITE", "Website"),
                            ("TELEGRAM", "Telegram"),
                        ],
                        default="WEBSITE",
                        help_text="Physically implemented provider.",
                        max_length=20,
                        verbose_name="physical provider",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="is enabled"),
                ),
            ],
            options={
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("title_en", models.CharField(max_length=250, null=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Notification content.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="Notification content.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Notification should shown at date and time.",
                        null=True,
                        verbose_name="triggered at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "providers",
                    models.ManyToManyField(
                        related_name="notifications",
                        to="notifications.notificationprovider",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="User read message.",
                        verbose_name="is read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="User read message at date and time.",
                        verbose_name="read at",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "notification")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                through="notifications.NotificationRecipient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
