# Generated by Django 5.2.8 on 2026-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationrecipient",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="User read message at date and time.",
                null=True,
                verbose_name="read at",
            ),
        ),
    ]
