# Generated by Django 5.2.8 on 2026-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notificationrecipient_read_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_shown",
            field=models.BooleanField(
                default=False,
                help_text="Was this notification shown?",
                verbose_name="is shown",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="triggered_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Notification should be shown at date and time.",
                null=True,
                verbose_name="trigger at",
            ),
        ),
    ]
