# Generated by Django 5.2.8 on 2026-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_is_shown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="audience",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("GROUP", "Group"),
                    ("PERSONAL", "Personal"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
