# Generated by Django 5.2.8 on 2026-01-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_audience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationprovider",
            name="physical_provider",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("WEBSITE", "Website"),
                    ("TELEGRAM", "Telegram"),
                    ("PUSH", "Push"),
                ],
                default="WEBSITE",
                help_text="Physically implemented provider.",
                max_length=20,
                verbose_name="physical provider",
            ),
        ),
    ]
