# Generated by Django 5.2.8 on 2026-01-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notificationprovider_physical_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Update"),
                    ("REMINDER", "Reminder"),
                    ("SYSTEM", "System"),
                    ("SOCIAL", "Social"),
                    ("ALERT", "Alert"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
