# Generated by Django 5.2.8 on 2026-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Notification subtitle (subtitle used in website-notifications, you can see it under the title).",
                max_length=250,
                null=True,
                verbose_name="subtitle",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Update"),
                    ("REMINDER", "Reminder"),
                    ("SYSTEM", "System"),
                    ("SOCIAL", "Social"),
                    ("ALERT", "Alert"),
                    ("SUCCESS", "Success"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
    ]
