# Generated by Django 5.2.8 on 2026-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_notification_subtitle_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="Notification subtitle (subtitle used in website and push notifications, you can see it under the title).",
                max_length=250,
                null=True,
                verbose_name="subtitle",
            ),
        ),
    ]
