# Generated by Django 5.2.8 on 2026-02-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notification_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content_uk",
            field=models.TextField(
                blank=True,
                help_text="Notification content.",
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_uk",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
