# Generated by Django 5.2.8 on 2026-03-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_notification_content_uk_notification_title_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="content_ru",
            field=models.TextField(
                blank=True,
                help_text="Notification content.",
                null=True,
                verbose_name="content",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_ru",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
