# Generated by Django 5.2.8 on 2026-05-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0010_notification_content_ru_notification_title_ru"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="subtitle_en",
            field=models.CharField(
                blank=True,
                help_text="Notification subtitle (subtitle used in website and push notifications, you can see it under the title).",
                max_length=250,
                null=True,
                verbose_name="subtitle",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="subtitle_ru",
            field=models.CharField(
                blank=True,
                help_text="Notification subtitle (subtitle used in website and push notifications, you can see it under the title).",
                max_length=250,
                null=True,
                verbose_name="subtitle",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="subtitle_uk",
            field=models.CharField(
                blank=True,
                help_text="Notification subtitle (subtitle used in website and push notifications, you can see it under the title).",
                max_length=250,
                null=True,
                verbose_name="subtitle",
            ),
        ),
    ]
