# Generated by Django 5.1.2 on 2024-12-07 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0021_alter_notification_title_alter_notification_title_en_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.CharField(
                choices=[("NOTIFICATION", "NOTIFICATION")],
                default="NOTIFICATION",
                help_text="Icon of the notification.",
                verbose_name="icon",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_shown",
            field=models.BooleanField(
                default=False,
                help_text="Notification is already shown.",
                verbose_name="shown",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(
                help_text="Message of the notification.", verbose_name="message"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message_en",
            field=models.TextField(
                help_text="Message of the notification.",
                null=True,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message_uk",
            field=models.TextField(
                help_text="Message of the notification.",
                null=True,
                verbose_name="message",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                help_text="Recipients of the notification.",
                through="notifications.NotificationStatus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="show_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Planned time to show.",
                verbose_name="show at",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(help_text="", max_length=150, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title_en",
            field=models.CharField(
                help_text="", max_length=150, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title_uk",
            field=models.CharField(
                help_text="", max_length=150, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("PERSONAL", "PERSONAL"),
                    ("GROUP", "GROUP"),
                    ("SYSTEM", "SYSTEM"),
                ],
                default="SYSTEM",
                help_text="Type of the notification.",
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="is_read",
            field=models.BooleanField(default=False, help_text="", verbose_name="Read"),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="notification",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.notification",
                verbose_name="Notification",
            ),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="user",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipient",
            ),
        ),
    ]
