# Generated by Django 5.2.8 on 2026-03-31 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stats", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="title")),
                (
                    "title_en",
                    models.CharField(max_length=250, null=True, verbose_name="title"),
                ),
                (
                    "title_uk",
                    models.CharField(max_length=250, null=True, verbose_name="title"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=250, null=True, verbose_name="title"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle of the newsletter.",
                        max_length=250,
                        null=True,
                        verbose_name="subtitle",
                    ),
                ),
                (
                    "subtitle_en",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle of the newsletter.",
                        max_length=250,
                        null=True,
                        verbose_name="subtitle",
                    ),
                ),
                (
                    "subtitle_uk",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle of the newsletter.",
                        max_length=250,
                        null=True,
                        verbose_name="subtitle",
                    ),
                ),
                (
                    "subtitle_ru",
                    models.CharField(
                        blank=True,
                        help_text="Subtitle of the newsletter.",
                        max_length=250,
                        null=True,
                        verbose_name="subtitle",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Newsletter content.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        blank=True,
                        help_text="Newsletter content.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        blank=True,
                        help_text="Newsletter content.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_ru",
                    models.TextField(
                        blank=True,
                        help_text="Newsletter content.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                ("published_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "views",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stats.views",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
