# Generated by Django 5.2.8 on 2026-03-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="published at"
            ),
        ),
    ]
