# Generated by Django 5.2.8 on 2026-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="type",
            field=models.CharField(
                choices=[
                    ("UPDATE", "Update"),
                    ("REMINDER", "Reminder"),
                    ("SYSTEM", "System"),
                    ("SOCIAL", "Social"),
                    ("ALERT", "Alert"),
                    ("SUCCESS", "Success"),
                ],
                default="SYSTEM",
                help_text="Newsletter type.",
                max_length=20,
                verbose_name="type",
            ),
        ),
    ]
