# Generated by Django 5.2.8 on 2026-04-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_news_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="has_more",
            field=models.BooleanField(
                default=False,
                help_text="Whether the newsletter has more content.",
                verbose_name="has more",
            ),
        ),
    ]
