# Generated by Django 5.2.8 on 2026-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_has_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="has_more",
            field=models.BooleanField(
                default=False,
                help_text='Show "Read more" button on the newsletter.',
                verbose_name="has more",
            ),
        ),
    ]
