# Generated by Django 5.2.8 on 2026-03-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tag_en",
            field=models.SlugField(
                max_length=100, null=True, unique=True, verbose_name="tag"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_ru",
            field=models.SlugField(
                max_length=100, null=True, unique=True, verbose_name="tag"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_uk",
            field=models.SlugField(
                max_length=100, null=True, unique=True, verbose_name="tag"
            ),
        ),
    ]
