# Generated by Django 5.2.8 on 2026-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_tag_tag_en_tag_tag_ru_tag_tag_uk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="tag"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_en",
            field=models.CharField(
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_ru",
            field=models.CharField(
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="tag",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_uk",
            field=models.CharField(
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="tag",
            ),
        ),
    ]
