# Generated by Django 5.0.8 on 2024-08-22 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Object creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Object updated date and time.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[("NONE", "NONE")],
                        default="NONE",
                        help_text="Security level of the area.",
                        max_length=50,
                        verbose_name="Security Level",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area that contains current area.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="abandoned.abandonedarea",
                        verbose_name="Parent Area",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="areas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.CreateModel(
            name="AbandonedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from general users and available only for admins.",
                        verbose_name="Hidden",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[("NONE", "NONE")],
                        default="NONE",
                        help_text="Security level of the object.",
                        max_length=50,
                        verbose_name="Security Level",
                    ),
                ),
                (
                    "preservation_level",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("DANGEROUS", "DANGEROUS"),
                        ],
                        default="HIGH",
                        help_text="Preservation level of the object.",
                        max_length=50,
                        verbose_name="Preservation Level",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("NEWBIE", "NEWBIE"),
                            ("EASY", "EASY"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                        ],
                        default="NEWBIE",
                        help_text="Difficulty level of the object.",
                        max_length=50,
                        verbose_name="Difficulty Level",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Object creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Object updated date and time.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "built_at",
                    models.DateField(
                        blank=True,
                        help_text="Object built date and time.",
                        null=True,
                        verbose_name="Built At",
                    ),
                ),
                (
                    "abandoned_at",
                    models.DateField(
                        blank=True,
                        help_text="When object became abandoned date and time.",
                        null=True,
                        verbose_name="Abandoned At",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area that contains current object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="abandoned.abandonedarea",
                        verbose_name="Area",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="objects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Object",
                "verbose_name_plural": "Objects",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Event creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="Date and time of start of trip.",
                        verbose_name="Start Datetime",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="Date and time of end of trip.",
                        verbose_name="End Datetime",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "PLANNED"),
                            ("IN_PROCESS", "IN PROCESS"),
                            ("FINISHED", "FINISHED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="PLANNED",
                        max_length=100,
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "REQUESTED"),
                            ("PLANNED", "PLANNED"),
                            ("PARTICIPATED", "PARTICIPATED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="REQUESTED",
                        max_length=100,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abandoned.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                help_text="Users that participate in this trip.",
                related_name="events",
                through="abandoned.Participation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
        migrations.CreateModel(
            name="ParticipationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Report creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        help_text="Report destination participation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="abandoned.participation",
                        verbose_name="Participation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
    ]
