# Generated by Django 5.1 on 2024-08-20 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area that contains current area.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="abandoned.abandonedarea",
                        verbose_name="Parent Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
            },
        ),
        migrations.CreateModel(
            name="AbandonedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Area that contains current object.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="abandoned.abandonedarea",
                        verbose_name="Area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Object",
                "verbose_name_plural": "Objects",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Event creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="Date and time of start of trip.",
                        verbose_name="Start Datetime",
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="Date and time of end of trip.",
                        verbose_name="End Datetime",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="my_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Organizer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.CreateModel(
            name="AttendanceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Report creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Report destination event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="abandoned.event",
                        verbose_name="Event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_requested",
                    models.BooleanField(
                        default=False,
                        help_text="User requested participation.",
                        verbose_name="Requested",
                    ),
                ),
                (
                    "is_attended",
                    models.BooleanField(
                        default=False,
                        help_text="The user marked himself as attendee.",
                        verbose_name="Attended",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Attendance was confirmed by other participants.",
                        verbose_name="Confirmed",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abandoned.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                help_text="Users that participate in this trip.",
                related_name="events",
                through="abandoned.Participant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
    ]
