# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.utils.timezone
import mdeditor.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbandonedArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("YES", "YES"),
                            ("YES_WITH_DOGS", "YES WITH DOGS"),
                            ("YES_WITH_WEAPONS", "YES WITH WEAPONS"),
                            ("YES_MILITARY", "YES_MILITARY"),
                        ],
                        default="NO",
                        help_text="security level of the area.",
                        verbose_name="security level",
                    ),
                ),
            ],
            options={
                "verbose_name": "area",
                "verbose_name_plural": "areas",
            },
        ),
        migrations.CreateModel(
            name="AbandonedObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Short description of the abandoned object for the objects page.",
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        help_text="Short description of the abandoned object for the objects page.",
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_uk",
                    models.CharField(
                        help_text="Short description of the abandoned object for the objects page.",
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "description",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("YES", "YES"),
                            ("YES_WITH_DOGS", "YES WITH DOGS"),
                            ("YES_WITH_WEAPONS", "YES WITH WEAPONS"),
                            ("YES_MILITARY", "YES_MILITARY"),
                        ],
                        default="NO",
                        help_text="Security level of the object.",
                        verbose_name="security Level",
                    ),
                ),
                (
                    "preservation_level",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("DANGEROUS", "DANGEROUS"),
                        ],
                        default="HIGH",
                        help_text="Preservation level of the object.",
                        verbose_name="preservation Level",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("NEWBIE", "NEWBIE"),
                            ("EASY", "EASY"),
                            ("MEDIUM", "MEDIUM"),
                            ("HARD", "HARD"),
                            ("LEGEND", "LEGEND"),
                        ],
                        default="NEWBIE",
                        help_text="Difficulty level of the object.",
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "built_at",
                    models.DateField(
                        blank=True,
                        help_text="Object built date and time.",
                        null=True,
                        verbose_name="built at",
                    ),
                ),
                (
                    "abandoned_at",
                    models.DateField(
                        blank=True,
                        help_text="When object became abandoned date and time.",
                        null=True,
                        verbose_name="abandoned at",
                    ),
                ),
            ],
            options={
                "verbose_name": "object",
                "verbose_name_plural": "objects",
            },
        ),
        migrations.CreateModel(
            name="AbandonedObjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AbandonedObjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the object category.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the object category.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the object category.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the object category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the object category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the object category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the event.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Short description of the event for the events page.",
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        help_text="Short description of the event for the events page.",
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_uk",
                    models.CharField(
                        help_text="Short description of the event for the events page.",
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="Date and time of start of trip.",
                        verbose_name="start at",
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        help_text="Date and time of end of trip.", verbose_name="end at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "PLANNED"),
                            ("IN_PROCESS", "IN PROCESS"),
                            ("FINISHED", "FINISHED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="PLANNED",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.CreateModel(
            name="HistoricalAbandonedArea",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the abandoned area.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the abandoned area.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("YES", "YES"),
                            ("YES_WITH_DOGS", "YES WITH DOGS"),
                            ("YES_WITH_WEAPONS", "YES WITH WEAPONS"),
                            ("YES_MILITARY", "YES_MILITARY"),
                        ],
                        default="NO",
                        help_text="security level of the area.",
                        verbose_name="security level",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical area",
                "verbose_name_plural": "historical areas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAbandonedObject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the abandoned object.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        help_text="Short description of the abandoned object for the objects page.",
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        help_text="Short description of the abandoned object for the objects page.",
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "short_description_uk",
                    models.CharField(
                        help_text="Short description of the abandoned object for the objects page.",
                        null=True,
                        verbose_name="short description",
                    ),
                ),
                (
                    "description",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    mdeditor.fields.MDTextField(
                        blank=True,
                        help_text="Description of the abandoned object.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "security_level",
                    models.CharField(
                        choices=[
                            ("NO", "NO"),
                            ("YES", "YES"),
                            ("YES_WITH_DOGS", "YES WITH DOGS"),
                            ("YES_WITH_WEAPONS", "YES WITH WEAPONS"),
                            ("YES_MILITARY", "YES_MILITARY"),
                        ],
                        default="NO",
                        help_text="Security level of the object.",
                        verbose_name="security Level",
                    ),
                ),
                (
                    "preservation_level",
                    models.CharField(
                        choices=[
                            ("LOW", "LOW"),
                            ("MEDIUM", "MEDIUM"),
                            ("HIGH", "HIGH"),
                            ("DANGEROUS", "DANGEROUS"),
                        ],
                        default="HIGH",
                        help_text="Preservation level of the object.",
                        verbose_name="preservation Level",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("NEWBIE", "NEWBIE"),
                            ("EASY", "EASY"),
                            ("MEDIUM", "MEDIUM"),
                            ("HARD", "HARD"),
                            ("LEGEND", "LEGEND"),
                        ],
                        default="NEWBIE",
                        help_text="Difficulty level of the object.",
                        verbose_name="difficulty level",
                    ),
                ),
                (
                    "built_at",
                    models.DateField(
                        blank=True,
                        help_text="Object built date and time.",
                        null=True,
                        verbose_name="built at",
                    ),
                ),
                (
                    "abandoned_at",
                    models.DateField(
                        blank=True,
                        help_text="When object became abandoned date and time.",
                        null=True,
                        verbose_name="abandoned at",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical object",
                "verbose_name_plural": "historical objects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCategory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the object category.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the object category.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the object category.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the object category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the object category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the object category.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical category",
                "verbose_name_plural": "historical categories",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalParticipationReport",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Report creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical report",
                "verbose_name_plural": "historical reports",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "REQUESTED"),
                            ("PLANNED", "PLANNED"),
                            ("PARTICIPATED", "PARTICIPATED"),
                            ("CONFIRMED", "CONFIRMED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="REQUESTED",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
            },
        ),
        migrations.CreateModel(
            name="ParticipationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Report creation date and time.",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
            },
        ),
    ]
