# Generated by Django 5.1 on 2024-08-20 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abandonedarea",
            options={"verbose_name": "Area", "verbose_name_plural": "Areas"},
        ),
        migrations.AlterModelOptions(
            name="abandonedobject",
            options={"verbose_name": "Object", "verbose_name_plural": "Objects"},
        ),
        migrations.AlterField(
            model_name="abandonedarea",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Area that contains current area.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="abandoned.abandonedarea",
                verbose_name="Parent Area",
            ),
        ),
        migrations.AlterField(
            model_name="abandonedobject",
            name="area",
            field=models.ForeignKey(
                help_text="Area that contains current object.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects",
                to="abandoned.abandonedarea",
                verbose_name="Area",
            ),
        ),
    ]
