# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("abandoned", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedarea",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="abandonedarea",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Area that contains current area.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="abandoned.abandonedarea",
                verbose_name="parent area",
            ),
        ),
    ]
