# Generated by Django 5.0.8 on 2024-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedarea",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned area.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="abandonedarea",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned area.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="abandonedarea",
            name="name_en",
            field=models.CharField(
                help_text="Name of the abandoned area.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedarea",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the abandoned area.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
