# Generated by Django 5.1 on 2024-08-20 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Participant",
            new_name="Participation",
        ),
        migrations.AlterModelOptions(
            name="participation",
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
    ]
