# Generated by Django 5.2.6 on 2025-10-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned object.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned object.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="name",
            field=models.CharField(
                default="",
                help_text="Name of the place.",
                max_length=250,
                verbose_name="name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="area",
            name="name_en",
            field=models.CharField(
                help_text="Name of the place.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
