# Generated by Django 5.0.8 on 2024-08-23 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0002_abandonedarea_description_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="abandonedobject",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Area that contains current object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abandoned_objects",
                to="abandoned.abandonedarea",
                verbose_name="Area",
            ),
        ),
        migrations.AlterField(
            model_name="abandonedobject",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="abandoned_objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
    ]
