# Generated by Django 5.1 on 2024-08-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0002_rename_participant_participation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participation",
            name="is_attended",
        ),
        migrations.RemoveField(
            model_name="participation",
            name="is_confirmed",
        ),
        migrations.RemoveField(
            model_name="participation",
            name="is_requested",
        ),
        migrations.AddField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("PLANNED", "PLANNED"),
                    ("ATTENDED", "ATTENDED"),
                    ("CONFIRMED", "CONFIRMED"),
                ],
                default="REQUESTED",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ParticipationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Report creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        help_text="Report destination participation.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="abandoned.participation",
                        verbose_name="Participation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
        migrations.DeleteModel(
            name="AttendanceReport",
        ),
    ]
