# Generated by Django 5.1 on 2024-08-20 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0002_alter_event_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                help_text="Users that participate in this trip.",
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participants",
            ),
        ),
    ]
