# Generated by Django 5.1 on 2024-08-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0002_alter_abandonedarea_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abandonedobject",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Area that contains current object.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects",
                to="abandoned.abandonedarea",
                verbose_name="Area",
            ),
        ),
    ]
