# Generated by Django 5.2.6 on 2025-10-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0002_area_description_area_description_en_area_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placesecurity",
            name="level",
            field=models.CharField(
                choices=[
                    ("NONE", "No Security"),
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                    ("EXTREME", "Extreme"),
                ],
                default="NONE",
                help_text="Current security level based on community feedbacks.",
                max_length=10,
                verbose_name="level",
            ),
        ),
    ]
