# Generated by Django 5.2.6 on 2025-10-18 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0003_alter_placesecurity_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent area.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="abandoned.area",
                verbose_name="parent",
            ),
        ),
    ]
