# Generated by Django 5.1 on 2024-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0003_alter_abandonedobject_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedobject",
            name="name",
            field=models.CharField(
                default="test",
                help_text="Name of the abandoned object.",
                max_length=250,
                verbose_name="Name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_af",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ar",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ar_dz",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ast",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_az",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_be",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_bg",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_bn",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_br",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_bs",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ca",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ckb",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_cs",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_cy",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_da",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_de",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_dsb",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_el",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_en",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_en_au",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_en_gb",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_eo",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_es",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_es_ar",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_es_co",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_es_mx",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_es_ni",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_es_ve",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_et",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_eu",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_fa",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_fi",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_fr",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_fy",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ga",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_gd",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_gl",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_he",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_hi",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_hr",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_hsb",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_hu",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_hy",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ia",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ig",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ind",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_io",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_is",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_it",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ja",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ka",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_kab",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_kk",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_km",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_kn",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ko",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ky",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_lb",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_lt",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_lv",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_mk",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ml",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_mn",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_mr",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ms",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_my",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_nb",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ne",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_nl",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_nn",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_os",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_pa",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_pl",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_pt",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_pt_br",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ro",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ru",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sk",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sl",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sq",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sr",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sr_latn",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sv",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_sw",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ta",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_te",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_tg",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_th",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_tk",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_tr",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_tt",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_udm",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ug",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_ur",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_uz",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_vi",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_zh_hans",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="name_zh_hant",
            field=models.CharField(
                help_text="Name of the abandoned object.",
                max_length=250,
                null=True,
                verbose_name="Name",
            ),
        ),
    ]
