# Generated by Django 5.1.1 on 2024-09-07 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0003_alter_abandonedobject_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="end_datetime",
        ),
        migrations.RemoveField(
            model_name="event",
            name="start_datetime",
        ),
        migrations.AddField(
            model_name="event",
            name="end_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time of end of trip.",
                verbose_name="End At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date and time of start of trip.",
                verbose_name="Start At",
            ),
            preserve_default=False,
        ),
    ]
