# Generated by Django 5.1 on 2024-08-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0003_remove_participation_is_attended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "PLANNED"),
                    ("FINISHED", "FINISHED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PLANNED",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("PLANNED", "PLANNED"),
                    ("PARTICIPATED", "PARTICIPATED"),
                    ("CONFIRMED", "CONFIRMED"),
                ],
                default="REQUESTED",
                max_length=100,
            ),
        ),
    ]
