# Generated by Django 5.2.8 on 2026-01-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0003_area_is_private_place_is_private"),
        ("geo", "0004_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="places",
                to="geo.address",
                verbose_name="address",
            ),
        ),
    ]
