# Generated by Django 5.2.8 on 2026-01-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0004_place_address"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.file"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abandoned.place",
                    ),
                ),
            ],
            options={
                "unique_together": {("file", "place")},
            },
        ),
        migrations.AddField(
            model_name="place",
            name="files",
            field=models.ManyToManyField(
                blank=True,
                related_name="places",
                through="abandoned.PlaceFile",
                to="media.file",
            ),
        ),
    ]
