# Generated by Django 5.1 on 2024-08-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0004_event_status_alter_participation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedobject",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned object.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned object.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned object.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="difficulty_level",
            field=models.CharField(
                choices=[
                    ("NEWBIE", "NEWBIE"),
                    ("EASY", "EASY"),
                    ("MEDIUM", "MEDIUM"),
                    ("HIGH", "HIGH"),
                ],
                default="NEWBIE",
                help_text="Difficulty level of the object.",
                max_length=50,
                verbose_name="Difficulty Level",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden from general users and available only for admins.",
                verbose_name="Hidden",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="preservation_level",
            field=models.CharField(
                choices=[
                    ("LOW", "LOW"),
                    ("MEDIUM", "MEDIUM"),
                    ("HIGH", "HIGH"),
                    ("DANGEROUS", "DANGEROUS"),
                ],
                default="HIGH",
                help_text="Preservation level of the object.",
                max_length=50,
                verbose_name="Preservation Level",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="security_level",
            field=models.CharField(
                choices=[("NONE", "NONE")],
                default="NONE",
                help_text="Security level of the object.",
                max_length=50,
                verbose_name="Security Level",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "PLANNED"),
                    ("IN_PROCESS", "IN PROCESS"),
                    ("FINISHED", "FINISHED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PLANNED",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("PLANNED", "PLANNED"),
                    ("PARTICIPATED", "PARTICIPATED"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="REQUESTED",
                max_length=100,
            ),
        ),
    ]
