# Generated by Django 5.1 on 2024-08-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0005_remove_abandonedobject_name_af_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedarea",
            name="name",
            field=models.CharField(
                default="test",
                help_text="Name of the abandoned area.",
                max_length=250,
                verbose_name="Name",
            ),
            preserve_default=False,
        ),
    ]
