# Generated by Django 5.1 on 2024-08-21 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0005_abandonedobject_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedobject",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Report creation date and time.",
                verbose_name="Created At",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Report creation date and time.",
                verbose_name="Updated At",
            ),
        ),
    ]
