# Generated by Django 5.2.8 on 2026-02-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0005_placefile_place_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFavoritePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abandoned.place",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "place")},
            },
        ),
        migrations.AddField(
            model_name="place",
            name="favorite_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_places",
                through="abandoned.UserFavoritePlace",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
