# Generated by Django 5.1 on 2024-08-21 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0006_abandonedobject_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abandonedobject",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Object creation date and time.",
                verbose_name="Created At",
            ),
        ),
        migrations.AlterField(
            model_name="abandonedobject",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Object updated date and time.",
                verbose_name="Updated At",
            ),
        ),
    ]
