# Generated by Django 5.2.8 on 2026-02-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0006_userfavoriteplace_place_favorite_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the abandoned object.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the place.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the place.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the place.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
