# Generated by Django 5.1 on 2024-08-21 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0007_alter_abandonedobject_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedobject",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="abandonedobject",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Object creation date and time.",
                verbose_name="Created At",
            ),
        ),
    ]
