# Generated by Django 5.2.8 on 2026-02-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0007_area_description_uk_area_name_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_supposed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this place is supposed to be abandoned.",
                verbose_name="is supposed",
            ),
        ),
    ]
