# Generated by Django 5.1 on 2024-08-22 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0008_abandonedobject_creator_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="abandonedobject",
            name="abandoned_at",
            field=models.DateField(
                blank=True,
                help_text="Object built date and time.",
                null=True,
                verbose_name="Built At",
            ),
        ),
        migrations.AddField(
            model_name="abandonedobject",
            name="built_at",
            field=models.DateField(
                blank=True,
                help_text="Object built date and time.",
                null=True,
                verbose_name="Built At",
            ),
        ),
        migrations.AlterField(
            model_name="abandonedobject",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="objects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="abandonedobject",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Object updated date and time.",
                verbose_name="Updated At",
            ),
        ),
    ]
