# Generated by Django 5.2.8 on 2026-02-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0008_place_is_supposed"),
    ]

    operations = [
        migrations.AddField(
            model_name="placepreservation",
            name="has_doors",
            field=models.BooleanField(
                default=True, help_text="Has doors?", verbose_name="has doors"
            ),
        ),
        migrations.AddField(
            model_name="placepreservation",
            name="has_floor",
            field=models.BooleanField(
                default=True, help_text="Has floor?", verbose_name="has floor"
            ),
        ),
        migrations.AddField(
            model_name="placepreservation",
            name="has_internal_ceilings",
            field=models.BooleanField(
                default=True,
                help_text="Has internal ceilings?",
                verbose_name="has internal ceilings",
            ),
        ),
        migrations.AddField(
            model_name="placepreservation",
            name="has_roof",
            field=models.BooleanField(
                default=True, help_text="Has roof?", verbose_name="has roof"
            ),
        ),
        migrations.AddField(
            model_name="placepreservation",
            name="has_walls",
            field=models.BooleanField(
                default=True, help_text="Has walls?", verbose_name="has walls"
            ),
        ),
        migrations.AddField(
            model_name="placepreservation",
            name="has_windows",
            field=models.BooleanField(
                default=True, help_text="Has windows?", verbose_name="has windows"
            ),
        ),
    ]
