# Generated by Django 5.2.8 on 2026-02-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0010_alter_placepreservation_has_doors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placesecurity",
            name="has_cameras",
            field=models.BooleanField(
                default=False, help_text="Has cameras?", verbose_name="has cameras"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_dogs",
            field=models.BooleanField(
                default=False, help_text="Has dogs?", verbose_name="has dogs"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_security",
            field=models.BooleanField(
                default=False, help_text="Has security?", verbose_name="has security"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_sensors",
            field=models.BooleanField(
                default=False, help_text="Has sensors?", verbose_name="has sensors"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_weapons",
            field=models.BooleanField(
                default=False, help_text="Has weapons?", verbose_name="has weapons"
            ),
        ),
    ]
