# Generated by Django 5.2.8 on 2026-02-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0011_placesecurity_has_cameras_placesecurity_has_dogs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placesecurity",
            name="has_cameras",
        ),
        migrations.RemoveField(
            model_name="placesecurity",
            name="has_dogs",
        ),
        migrations.RemoveField(
            model_name="placesecurity",
            name="has_sensors",
        ),
        migrations.RemoveField(
            model_name="placesecurity",
            name="has_weapons",
        ),
        migrations.RemoveField(
            model_name="placesecurity",
            name="level",
        ),
    ]
