# Generated by Django 5.2.8 on 2026-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0012_remove_placesecurity_has_cameras_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placesecurity",
            name="has_cameras",
            field=models.BooleanField(
                default=False, help_text="Has cameras?", verbose_name="has cameras"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_dogs",
            field=models.BooleanField(
                default=False, help_text="Has dogs?", verbose_name="has dogs"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_sensors",
            field=models.BooleanField(
                default=False, help_text="Has sensors?", verbose_name="has sensors"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="has_weapons",
            field=models.BooleanField(
                default=False, help_text="Has weapons?", verbose_name="has weapons"
            ),
        ),
        migrations.AddField(
            model_name="placesecurity",
            name="level",
            field=models.CharField(
                choices=[
                    ("NONE", "No Security"),
                    ("EASY", "Easy"),
                    ("MEDIUM", "Medium"),
                    ("HARD", "Hard"),
                    ("IMPOSSIBLE", "Impossible"),
                ],
                default="NONE",
                help_text="Current security level based on community feedbacks.",
                max_length=10,
                verbose_name="level",
            ),
        ),
    ]
