# Generated by Django 5.2.8 on 2026-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0013_placesecurity_has_cameras_placesecurity_has_dogs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placepreservation",
            name="has_doors",
            field=models.BooleanField(
                default=False, help_text="Has doors?", verbose_name="doors"
            ),
        ),
        migrations.AlterField(
            model_name="placepreservation",
            name="has_floor",
            field=models.BooleanField(
                default=False, help_text="Has floor?", verbose_name="floor"
            ),
        ),
        migrations.AlterField(
            model_name="placepreservation",
            name="has_internal_ceilings",
            field=models.BooleanField(
                default=False,
                help_text="Has internal ceilings?",
                verbose_name="internal ceilings",
            ),
        ),
        migrations.AlterField(
            model_name="placepreservation",
            name="has_roof",
            field=models.BooleanField(
                default=False, help_text="Has roof?", verbose_name="roof"
            ),
        ),
        migrations.AlterField(
            model_name="placepreservation",
            name="has_walls",
            field=models.BooleanField(
                default=False, help_text="Has walls?", verbose_name="walls"
            ),
        ),
        migrations.AlterField(
            model_name="placepreservation",
            name="has_windows",
            field=models.BooleanField(
                default=False, help_text="Has windows?", verbose_name="windows"
            ),
        ),
        migrations.AlterField(
            model_name="placesecurity",
            name="has_cameras",
            field=models.BooleanField(
                default=False, help_text="Has cameras?", verbose_name="cameras"
            ),
        ),
        migrations.AlterField(
            model_name="placesecurity",
            name="has_dogs",
            field=models.BooleanField(
                default=False, help_text="Has dogs?", verbose_name="dogs"
            ),
        ),
        migrations.AlterField(
            model_name="placesecurity",
            name="has_security",
            field=models.BooleanField(
                default=False, help_text="Has security?", verbose_name="security"
            ),
        ),
        migrations.AlterField(
            model_name="placesecurity",
            name="has_sensors",
            field=models.BooleanField(
                default=False, help_text="Has sensors?", verbose_name="sensors"
            ),
        ),
        migrations.AlterField(
            model_name="placesecurity",
            name="has_weapons",
            field=models.BooleanField(
                default=False, help_text="Has weapons?", verbose_name="weapons"
            ),
        ),
    ]
