# Generated by Django 5.2.8 on 2026-02-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0014_alter_placepreservation_has_doors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="placepreservation",
            name="has_furniture",
            field=models.BooleanField(
                default=False, help_text="Has furniture?", verbose_name="furniture"
            ),
        ),
        migrations.AddField(
            model_name="placepreservation",
            name="is_clean",
            field=models.BooleanField(
                default=False, help_text="Is clean?", verbose_name="clean"
            ),
        ),
    ]
