# Generated by Django 5.2.8 on 2026-03-25 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0016_area_description_ru_area_name_ru_and_more"),
        ("stats", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="views",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stats.views",
            ),
        ),
    ]
