# Generated by Django 5.2.8 on 2026-04-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0018_provider_place_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Slug of the provider.",
                max_length=250,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
    ]
