# Generated by Django 5.2.8 on 2026-05-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0020_provider_created_by"),
        ("accounts", "0018_objectpermission_alter_referral_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="permission",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.objectpermission",
            ),
        ),
    ]
