# Generated by Django 5.2.8 on 2026-02-20 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_feedback_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Executor's comment related to the request.",
                        null=True,
                        verbose_name="comment",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        help_text="Context of the request.", verbose_name="context"
                    ),
                ),
                (
                    "is_fulfilled",
                    models.BooleanField(default=False, verbose_name="is fulfilled"),
                ),
                (
                    "fulfilled_at",
                    models.DateTimeField(
                        help_text="Date and time at which the request was fulfilled.",
                        verbose_name="fulfilled at",
                    ),
                ),
                (
                    "fulfilled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Executor who fulfilled the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests_fulfilled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="fulfilled by",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who requested the request.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests_requested",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requested by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
