# Generated by Django 5.2.8 on 2026-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0003_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="fulfilled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time at which the request was fulfilled.",
                null=True,
                verbose_name="fulfilled at",
            ),
        ),
    ]
