# Generated by Django 5.2.8 on 2026-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0004_alter_request_fulfilled_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="type",
            field=models.CharField(
                choices=[
                    ("CORRECTION", "Correction"),
                    ("COMPLAINT", "Complaint"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="Type of the request.",
                max_length=20,
            ),
        ),
    ]
