# Generated by Django 5.2.8 on 2026-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0005_request_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="path",
            field=models.CharField(
                blank=True,
                help_text="User path.",
                max_length=255,
                null=True,
                verbose_name="path",
            ),
        ),
    ]
