# Generated by Django 5.2.8 on 2026-03-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expeditions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expedition",
            name="finished_at",
        ),
        migrations.AddField(
            model_name="expedition",
            name="ended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="End date and time (planned or actual or cancel).",
                null=True,
                verbose_name="ended at",
            ),
        ),
    ]
