# Generated by Django 5.2.8 on 2026-03-18 20:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abandoned", "0016_area_description_ru_area_name_ru_and_more"),
        ("expeditions", "0002_remove_expedition_finished_at_expedition_ended_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("PLANNED", "Planned"),
                            ("PARTICIPATED", "Participated"),
                        ],
                        default="PLANNED",
                        verbose_name="state",
                    ),
                ),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="expeditions.expedition",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="Summary of the expedition from participant's point of view.",
                        null=True,
                        verbose_name="summary",
                    ),
                ),
                (
                    "is_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Participant surely took part in the expedition.",
                        verbose_name="is confirmed",
                    ),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="expeditions.participation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Waypoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Visited point (if place not specified).",
                        null=True,
                        srid=4326,
                        verbose_name="point",
                    ),
                ),
                (
                    "is_visited",
                    models.BooleanField(
                        default=False,
                        help_text="Expedition visited this point.",
                        verbose_name="is visited",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("POI", "POI"), ("MEETING", "Meeting")],
                        default="POI",
                        max_length=10,
                    ),
                ),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waypoints",
                        to="expeditions.expedition",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="abandoned.place",
                    ),
                ),
            ],
            options={
                "unique_together": {("expedition", "place", "point")},
            },
        ),
    ]
