# Generated by Django 5.2.8 on 2026-01-05 08:37

import cities_light.abstract_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="search_names",
            field=cities_light.abstract_models.ToSearchTextField(
                blank=True, default="", max_length=4000
            ),
        ),
    ]
