# Generated by Django 5.2.8 on 2026-01-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_alter_city_search_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Country is supported", verbose_name="is active"
            ),
        ),
    ]
