# Generated by Django 5.2.8 on 2026-01-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="region",
        ),
        migrations.RemoveField(
            model_name="address",
            name="subregion",
        ),
    ]
