# Generated by Django 5.2.8 on 2026-01-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0005_remove_address_region_remove_address_subregion"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.region",
                verbose_name="region",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="subregion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.subregion",
                verbose_name="subregion",
            ),
        ),
    ]
