# Generated by Django 5.2.8 on 2026-01-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0006_address_region_address_subregion"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="address"),
        ),
    ]
