# Generated by Django 5.2.8 on 2026-01-09 21:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0007_address_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Point of the city.",
                null=True,
                srid=4326,
                verbose_name="point",
            ),
        ),
    ]
