# Generated by Django 5.2.8 on 2026-01-12 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file.",
                        upload_to="media/",
                        verbose_name="file",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PHOTO", "PHOTO"),
                            ("VIDEO", "VIDEO"),
                            ("AUDIO", "AUDIO"),
                            ("DOCUMENT", "DOCUMENT"),
                            ("EXECUTABLE", "EXECUTABLE"),
                            ("OTHER", "OTHER"),
                        ],
                        default="OTHER",
                        help_text="File type.",
                        verbose_name="Type",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from general users and available only for admins and creator.",
                        verbose_name="Hidden",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded the file.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
