# Generated by Django 5.2.8 on 2026-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="type",
            field=models.CharField(
                choices=[
                    ("PHOTO", "Photo"),
                    ("VIDEO", "Video"),
                    ("AUDIO", "Audio"),
                    ("DOCUMENT", "Document"),
                    ("EXECUTABLE", "Executable"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                help_text="File type.",
                verbose_name="Type",
            ),
        ),
    ]
