# Generated by Django 5.1.2 on 2024-12-07 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_file_is_hidden_alter_file_creator_alter_file_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="File creation date and time.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="User who uploaded the file.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                help_text="Uploaded file.", upload_to="uploads/", verbose_name="file"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="File updated date and time.",
                verbose_name="updated at",
            ),
        ),
    ]
