# Generated by Django 5.1.1 on 2024-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[], help_text="Type of an action.", verbose_name="Type"
            ),
        ),
    ]
