# Generated by Django 5.0.8 on 2025-02-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0002_alter_action_data_alter_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREATED ABANDONED OBJECT", "CREATED ABANDONED OBJECT"),
                    ("CREATED ABANDONED AREA", "CREATED ABANDONED AREA"),
                    ("UPDATED ABANDONED OBJECT", "UPDATED ABANDONED OBJECT"),
                    ("UPDATED ABANDONED AREA", "UPDATED ABANDONED AREA"),
                ],
                help_text="Type of an action.",
                verbose_name="type",
            ),
        ),
    ]
