# Generated by Django 5.1.1 on 2024-09-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0002_alter_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="type",
            field=models.CharField(
                choices=[
                    ("REGISTERED", "REGISTERED"),
                    ("LOGGED IN", "LOGGED IN"),
                    ("LOGGED OUT", "LOGGED OUT"),
                    ("CREATED ABANDONED OBJECT", "CREATED ABANDONED OBJECT"),
                    ("CREATED ABANDONED AREA", "CREATED ABANDONED AREA"),
                    ("UPDATED ABANDONED OBJECT", "UPDATED ABANDONED OBJECT"),
                    ("UPDATED ABANDONED AREA", "UPDATED ABANDONED AREA"),
                ],
                help_text="Type of an action.",
                verbose_name="Type",
            ),
        ),
    ]
