# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.contrib.auth.validators
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Telegram user ID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="telegram ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username.",
                        max_length=150,
                        null=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Nickname of the user.",
                        max_length=150,
                        null=True,
                        verbose_name="nickname",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name in telegram.",
                        max_length=150,
                        null=True,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name in telegram.",
                        max_length=150,
                        null=True,
                        verbose_name="last name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the user.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="User joined at date and time.",
                        verbose_name="joined at",
                    ),
                ),
                (
                    "born_at",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="User born at date and time.",
                        null=True,
                        verbose_name="birth Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="User updated date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The experience of the user.",
                        verbose_name="experience",
                    ),
                ),
                (
                    "karma",
                    models.IntegerField(
                        default=0,
                        help_text="The karma of the user.",
                        verbose_name="karma",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Friendship request approving date and time.",
                        null=True,
                        verbose_name="approved at",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Friendship request has been approved.",
                        verbose_name="approved",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalRank",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=20)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the rank.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The name of the rank.",
                        max_length=100,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="The name of the rank.",
                        max_length=100,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rank",
                "verbose_name_plural": "historical Ranks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTeam",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the team.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team",
                "verbose_name_plural": "historical teams",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Telegram user ID",
                        verbose_name="telegram ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Telegram username.",
                        max_length=150,
                        null=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Nickname of the user.",
                        max_length=150,
                        null=True,
                        verbose_name="nickname",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        help_text="First name in telegram.",
                        max_length=150,
                        null=True,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        help_text="Last name in telegram.",
                        max_length=150,
                        null=True,
                        verbose_name="last name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the user.",
                        max_length=254,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="User joined at date and time.",
                        verbose_name="joined at",
                    ),
                ),
                (
                    "born_at",
                    models.DateField(
                        blank=True,
                        default=None,
                        help_text="User born at date and time.",
                        null=True,
                        verbose_name="birth Date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="User updated date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The experience of the user.",
                        verbose_name="experience",
                    ),
                ),
                (
                    "karma",
                    models.IntegerField(
                        default=0,
                        help_text="The karma of the user.",
                        verbose_name="karma",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical User",
                "verbose_name_plural": "historical Users",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                ("key", models.CharField(max_length=20, unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the rank.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="The name of the rank.",
                        max_length=100,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="The name of the rank.",
                        max_length=100,
                        null=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rank",
                "verbose_name_plural": "Ranks",
            },
        ),
        migrations.CreateModel(
            name="ReferralLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Code")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralLinkUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral Link Usage",
                "verbose_name_plural": "Referral Link Usages",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("uk", "Ukrainian")],
                        default="en",
                        help_text="Preferred language of the user.",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "is_animations_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable animations.",
                        verbose_name="animations",
                    ),
                ),
                (
                    "is_newsletters_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable newsletters.",
                        verbose_name="newsletters",
                    ),
                ),
                (
                    "is_notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable notifier.",
                        verbose_name="notifier",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("LIGHT", "LIGHT"), ("DARK", "DARK")],
                        default="LIGHT",
                        help_text="Preferred theme of the user.",
                        max_length=10,
                        verbose_name="theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the team.",
                        max_length=250,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "verbose_name": "team",
                "verbose_name_plural": "teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "team member",
                "verbose_name_plural": "team members",
            },
        ),
        migrations.CreateModel(
            name="Terms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Active version of Terms of Usage.",
                        verbose_name="active",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="0.0.1",
                        help_text="Version of Terms of Usage.",
                        unique=True,
                        verbose_name="version",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of Terms of Usage.", verbose_name="content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Content of Terms of Usage.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        help_text="Content of Terms of Usage.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terms of Usage",
                "verbose_name_plural": "Terms of Usage",
            },
        ),
    ]
