# Generated by Django 5.2.8 on 2025-12-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="slug",
            field=models.SlugField(
                default="",
                help_text="Slug of the achievement.",
                max_length=250,
                unique=True,
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="born_at",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="User born at date and time.",
                null=True,
                verbose_name="birth date",
            ),
        ),
    ]
