# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                help_text="The avatar of the user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.file",
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_friend_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="initiator",
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_friend_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient",
            ),
        ),
        migrations.AddField(
            model_name="historicalrank",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalteam",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The avatar of the user.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="media.file",
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The rank of the user.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.rank",
                verbose_name="rank",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                help_text="The rank of the user.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.rank",
                verbose_name="rank",
            ),
        ),
        migrations.AddField(
            model_name="referrallink",
            name="referrer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Referrer",
            ),
        ),
        migrations.AddField(
            model_name="referrallinkusage",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.referrallink"
            ),
        ),
        migrations.AddField(
            model_name="referrallinkusage",
            name="referral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="referrallink",
            name="referrals",
            field=models.ManyToManyField(
                blank=True,
                through="accounts.ReferralLinkUsage",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Referrals",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="user",
            field=models.OneToOneField(
                help_text="User settings.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="accounts.team",
                verbose_name="team",
            ),
        ),
        migrations.AddField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="terms",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User-author of this version of Terms of Usage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="referrallinkusage",
            unique_together={("link", "referral")},
        ),
    ]
