# Generated by Django 5.2.6 on 2025-10-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="is_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Notifications enabled.",
                verbose_name="notifications",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[("en", "English")],
                default="en",
                help_text="Preferred language of the user.",
                max_length=10,
                verbose_name="language",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="theme",
            field=models.CharField(
                choices=[("LIGHT", "Light"), ("DARK", "Dark")],
                default="DARK",
                help_text="Preferred theme of the user.",
                max_length=10,
                verbose_name="theme",
            ),
        ),
    ]
