# Generated by Django 5.2.8 on 2026-01-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_referral_referralcode_referral_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referral",
            options={"verbose_name": "Referral", "verbose_name_plural": "Referrals"},
        ),
        migrations.AlterModelOptions(
            name="referralcode",
            options={
                "verbose_name": "Referral Code",
                "verbose_name_plural": "Referral Codes",
            },
        ),
        migrations.AddField(
            model_name="referralcode",
            name="is_initial",
            field=models.BooleanField(
                default=False,
                help_text="User's initial referral code (given when user was created)",
                verbose_name="is initial",
            ),
        ),
        migrations.AddField(
            model_name="username",
            name="is_initial",
            field=models.BooleanField(
                default=False,
                help_text="User's initial username (given when user was created)",
                verbose_name="is initial",
            ),
        ),
    ]
