# Generated by Django 5.2.8 on 2026-01-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_referral_options_alter_referralcode_options_and_more"),
        ("geo", "0003_country_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="User country.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geo.country",
                verbose_name="country",
            ),
        ),
    ]
