# Generated by Django 5.2.6 on 2025-10-17 12:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="username",
            name="username",
            field=models.CharField(
                db_index=True,
                help_text="Unique user username.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
