# Generated by Django 5.2.6 on 2025-10-17 12:47

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_username_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="username",
            name="slug",
        ),
        migrations.AlterField(
            model_name="username",
            name="username",
            field=models.SlugField(
                help_text="Unique user username.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
