# Generated by Django 5.2.8 on 2026-01-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_settings_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="is_country_visible",
            field=models.BooleanField(
                default=True,
                help_text="User country is visible in profile.",
                verbose_name="is country visible",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="born_at",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="User birth date.",
                null=True,
                verbose_name="birth date",
            ),
        ),
    ]
