# Generated by Django 5.2.8 on 2026-01-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_settings_is_country_visible_alter_user_born_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="User is online right now.",
                verbose_name="is online",
            ),
        ),
    ]
