# Generated by Django 5.1.1 on 2024-09-07 17:19

import django.contrib.auth.validators
import django.db.models.deletion
import src.apps.accounts.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_teammember_team_alter_teammember_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="", max_length=150, verbose_name="Title"
                    ),
                ),
                ("message", models.TextField(help_text="", verbose_name="Message")),
                (
                    "type",
                    models.CharField(
                        choices=[("PERSONAL", "PERSONAL")],
                        default=src.apps.accounts.enums.NotificationType,
                        help_text="Type of the notification.",
                        verbose_name="Type",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[("NOTIFICATION", "NOTIFICATION")],
                        default="NOTIFICATION",
                        help_text="Icon of the notification.",
                        verbose_name="Icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="accounts.team",
                verbose_name="Team",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, help_text="", max_length=254, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="", max_length=150, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, help_text="", max_length=150, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="",
                max_length=150,
                null=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="useraction",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Action additional data.",
                null=True,
                verbose_name="Data",
            ),
        ),
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False, help_text="", verbose_name="Read"
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        help_text="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.notification",
                        verbose_name="Notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Status",
                "verbose_name_plural": "Notification Statuses",
                "unique_together": {("user", "notification")},
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                help_text="",
                through="accounts.NotificationStatus",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Recipients",
            ),
        ),
    ]
