# Generated by Django 5.2.8 on 2026-01-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="is_emails_enabled",
            field=models.BooleanField(
                default=True, help_text="Emails enabled.", verbose_name="emails"
            ),
        ),
    ]
