# Generated by Django 5.2.8 on 2026-02-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_settings_is_emails_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="is_interactive_mode_enabled",
            field=models.BooleanField(
                default=True,
                help_text="User will informational toasts, hints, and tooltips",
                verbose_name="is interactive mode enabled",
            ),
        ),
    ]
