# Generated by Django 5.2.8 on 2026-02-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_settings_is_interactive_mode_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the achievement.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the achievement.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("uk", "Ukrainian")],
                default="en",
                help_text="Preferred language of the user.",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
