# Generated by Django 5.2.8 on 2026-03-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_achievement_description_uk_achievement_name_uk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Description of the achievement.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="name_ru",
            field=models.CharField(
                help_text="Name of the achievement.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("uk", "Ukrainian"), ("ru", "Russian")],
                default="en",
                help_text="Preferred language of the user.",
                max_length=10,
                verbose_name="language",
            ),
        ),
    ]
