# Generated by Django 5.2.8 on 2026-03-20 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_achievement_description_ru_achievement_name_ru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the place.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the place.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the place.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Name of the place.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the place.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the place.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the place.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        blank=True,
                        help_text="Description of the place.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "motto",
                    models.TextField(
                        blank=True, help_text="Motto", null=True, verbose_name="motto"
                    ),
                ),
                (
                    "motto_en",
                    models.TextField(
                        blank=True, help_text="Motto", null=True, verbose_name="motto"
                    ),
                ),
                (
                    "motto_uk",
                    models.TextField(
                        blank=True, help_text="Motto", null=True, verbose_name="motto"
                    ),
                ),
                (
                    "motto_ru",
                    models.TextField(
                        blank=True, help_text="Motto", null=True, verbose_name="motto"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.team"
                    ),
                ),
            ],
            options={
                "unique_together": {("member", "team")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Members of the team.",
                through="accounts.TeamMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="members",
            ),
        ),
    ]
