# Generated by Django 5.2.8 on 2026-03-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_referral_user_team_teammember_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the team.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the team.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Description of the team.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the team.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="motto",
            field=models.TextField(
                blank=True,
                help_text="Motto of the team.",
                null=True,
                verbose_name="motto",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="motto_en",
            field=models.TextField(
                blank=True,
                help_text="Motto of the team.",
                null=True,
                verbose_name="motto",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="motto_ru",
            field=models.TextField(
                blank=True,
                help_text="Motto of the team.",
                null=True,
                verbose_name="motto",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="motto_uk",
            field=models.TextField(
                blank=True,
                help_text="Motto of the team.",
                null=True,
                verbose_name="motto",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                help_text="Name of the team.", max_length=250, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name_en",
            field=models.CharField(
                help_text="Name of the team.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name_ru",
            field=models.CharField(
                help_text="Name of the team.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the team.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
    ]
