# Generated by Django 5.2.8 on 2026-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_experiencetransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencetransaction",
            name="amount",
            field=models.PositiveBigIntegerField(default=0, verbose_name="amount"),
        ),
    ]
