# Generated by Django 5.2.8 on 2026-05-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_karmatransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="experience",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Experience reward of the achievement.",
                verbose_name="experience",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="karma",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Karma reward of the achievement.",
                verbose_name="karma",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="money",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Financial reaward of the achievement.",
                verbose_name="money",
            ),
        ),
    ]
