# Generated by Django 5.2.8 on 2026-05-20 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_achievement_experience_achievement_karma_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="referral",
            unique_together={("user", "code")},
        ),
        migrations.CreateModel(
            name="TeamObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_visible", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=False)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_object_permissions",
                        to="accounts.objectpermission",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.team"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["team", "is_visible"],
                        name="accounts_te_team_id_d719fb_idx",
                    ),
                    models.Index(
                        fields=["team", "is_editable"],
                        name="accounts_te_team_id_9fb408_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_visible", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=False)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_object_permissions",
                        to="accounts.objectpermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_visible"],
                        name="accounts_us_user_id_c790fb_idx",
                    ),
                    models.Index(
                        fields=["user", "is_editable"],
                        name="accounts_us_user_id_bcfa9d_idx",
                    ),
                ],
            },
        ),
    ]
