# Generated by Django 5.0.8 on 2025-02-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_alter_teammember_team_alter_teammember_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="name_en",
            field=models.CharField(
                help_text="The name of the rank.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="rank",
            name="name_uk",
            field=models.CharField(
                help_text="The name of the rank.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="accounts.team",
                verbose_name="team",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
