# Generated by Django 5.0.8 on 2025-02-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_user_rank_alter_teammember_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="key",
            field=models.SlugField(default="test", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(
                help_text="The name of the rank.", max_length=100, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name_en",
            field=models.CharField(
                help_text="The name of the rank.",
                max_length=100,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name_uk",
            field=models.CharField(
                help_text="The name of the rank.",
                max_length=100,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="accounts.team",
                verbose_name="team",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="user",
            field=models.ForeignKey(
                help_text="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
