# Generated by Django 5.0.8 on 2025-03-25 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_alter_teammember_team_alter_teammember_user_and_more"),
        ("accounts", "0045_alter_teammember_team_alter_teammember_user"),
    ]

    operations = []
