# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPostFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "file",
                "verbose_name_plural": "files",
            },
        ),
        migrations.CreateModel(
            name="BlogPostTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlogTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Topic creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="General user can't post to this topic.",
                        verbose_name="closed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.CreateModel(
            name="HistoricalBlogPost",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the blog post.",
                        max_length=250,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Title of the blog post.",
                        max_length=250,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Title of the blog post.",
                        max_length=250,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Brief summary of the post for the posts page.",
                        verbose_name="summary",
                    ),
                ),
                (
                    "summary_en",
                    models.CharField(
                        help_text="Brief summary of the post for the posts page.",
                        null=True,
                        verbose_name="summary",
                    ),
                ),
                (
                    "summary_uk",
                    models.CharField(
                        help_text="Brief summary of the post for the posts page.",
                        null=True,
                        verbose_name="summary",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the blog post.", verbose_name="content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Content of the blog post.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        help_text="Content of the blog post.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Post published (or planned publishing) date and time.",
                        verbose_name="published at",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Post",
                "verbose_name_plural": "historical Posts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBlogTopic",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        null=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Topic creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="General user can't post to this topic.",
                        verbose_name="closed",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Topic",
                "verbose_name_plural": "historical Topics",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Creation date and time.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Update date and time.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the blog post.",
                        max_length=250,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        help_text="Title of the blog post.",
                        max_length=250,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "title_uk",
                    models.CharField(
                        help_text="Title of the blog post.",
                        max_length=250,
                        null=True,
                        verbose_name="title",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Brief summary of the post for the posts page.",
                        verbose_name="summary",
                    ),
                ),
                (
                    "summary_en",
                    models.CharField(
                        help_text="Brief summary of the post for the posts page.",
                        null=True,
                        verbose_name="summary",
                    ),
                ),
                (
                    "summary_uk",
                    models.CharField(
                        help_text="Brief summary of the post for the posts page.",
                        null=True,
                        verbose_name="summary",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the blog post.", verbose_name="content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Content of the blog post.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        help_text="Content of the blog post.",
                        null=True,
                        verbose_name="content",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Post published (or planned publishing) date and time.",
                        verbose_name="published at",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Creator of the blog post.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
