# Generated by Django 5.1.1 on 2024-09-29 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the blog topic.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "description_uk",
                    models.TextField(
                        blank=True,
                        help_text="Description of the blog topic.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Topic creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hidden from general users and available only for admins and creator.",
                        verbose_name="Hidden",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the blog post.",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Name of the blog post.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        help_text="Name of the blog post.",
                        max_length=250,
                        null=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Content of the blog post.", verbose_name="Content"
                    ),
                ),
                (
                    "content_en",
                    models.TextField(
                        help_text="Content of the blog post.",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "content_uk",
                    models.TextField(
                        help_text="Content of the blog post.",
                        null=True,
                        verbose_name="Content",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Object creation date and time.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Object updated date and time.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic of the post.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.blogtopic",
                        verbose_name="Topic",
                    ),
                ),
            ],
        ),
    ]
