# Generated by Django 5.0.8 on 2025-05-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("blog", "0001_initial"),
        ("media", "0001_initial"),
        ("permissions", "0001_initial"),
        ("ratings", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="permissions",
            field=models.OneToOneField(
                blank=True,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.objectpermission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="viewable",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ratings.viewable",
                verbose_name="views",
            ),
        ),
        migrations.AddField(
            model_name="blogpostfile",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="media.file"
            ),
        ),
        migrations.AddField(
            model_name="blogpostfile",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpost"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="files",
            field=models.ManyToManyField(
                help_text="The media files attached to this blog post.",
                related_name="posts",
                through="blog.BlogPostFile",
                to="media.file",
                verbose_name="files",
            ),
        ),
        migrations.AddField(
            model_name="blogposttopic",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogpost"
            ),
        ),
        migrations.AddField(
            model_name="blogtopic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_topics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="blogtopic",
            name="permissions",
            field=models.OneToOneField(
                blank=True,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.objectpermission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="blogposttopic",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blogtopic"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="topics",
            field=models.ManyToManyField(
                blank=True,
                help_text="Topics of the post.",
                through="blog.BlogPostTopic",
                to="blog.blogtopic",
                verbose_name="topics",
            ),
        ),
        migrations.AddField(
            model_name="historicalblogpost",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalblogpost",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalblogpost",
            name="permissions",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="permissions.objectpermission",
                verbose_name="permissions",
            ),
        ),
        migrations.AddField(
            model_name="historicalblogpost",
            name="viewable",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="ratings.viewable",
                verbose_name="views",
            ),
        ),
        migrations.AddField(
            model_name="historicalblogtopic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="historicalblogtopic",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalblogtopic",
            name="permissions",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="permissions.objectpermission",
                verbose_name="permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogposttopic",
            unique_together={("post", "topic")},
        ),
    ]
