# Generated by Django 5.1.1 on 2024-09-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={"verbose_name": "Post", "verbose_name_plural": "Posts"},
        ),
        migrations.AddField(
            model_name="blogtopic",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hidden from general users and available only for admins and creator.",
                verbose_name="Hidden",
            ),
        ),
    ]
