# Generated by Django 5.1.1 on 2024-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_options_blogtopic_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogtopic",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="General user can't post to this topic.",
                verbose_name="Closed",
            ),
        ),
    ]
