# Generated by Django 5.1.1 on 2024-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpost_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="name",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="name_uk",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                default="Test",
                help_text="Title of the blog post.",
                max_length=250,
                verbose_name="Title",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(
                help_text="Title of the blog post.",
                max_length=250,
                null=True,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="title_uk",
            field=models.CharField(
                help_text="Title of the blog post.",
                max_length=250,
                null=True,
                verbose_name="Title",
            ),
        ),
    ]
