# Generated by Django 5.1.1 on 2024-10-06 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogtopic_creator"),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="permissions",
            field=models.OneToOneField(
                blank=True,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.objectpermission",
                verbose_name="Permissions",
            ),
        ),
    ]
