# Generated by Django 5.1.1 on 2024-10-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_blogtopic_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="is_hidden",
        ),
        migrations.RemoveField(
            model_name="blogtopic",
            name="is_hidden",
        ),
    ]
