# Generated by Django 5.1.2 on 2024-12-07 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_remove_blogpost_is_hidden_remove_blogtopic_is_hidden"),
        ("permissions", "0006_alter_modelpermission_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                help_text="Content of the blog post.", verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_en",
            field=models.TextField(
                help_text="Content of the blog post.", null=True, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content_uk",
            field=models.TextField(
                help_text="Content of the blog post.", null=True, verbose_name="content"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Post creation date and time.",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="permissions",
            field=models.OneToOneField(
                blank=True,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.objectpermission",
                verbose_name="permissions",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Post published (or planned publishing) date and time.",
                verbose_name="published at",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                help_text="Title of the blog post.",
                max_length=250,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title_en",
            field=models.CharField(
                help_text="Title of the blog post.",
                max_length=250,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title_uk",
            field=models.CharField(
                help_text="Title of the blog post.",
                max_length=250,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="topic",
            field=models.ForeignKey(
                help_text="Topic of the post.",
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.blogtopic",
                verbose_name="topic",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Post updated date and time.",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_topics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the blog topic.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Description of the blog topic.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="description_uk",
            field=models.TextField(
                blank=True,
                help_text="Description of the blog topic.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="General user can't post to this topic.",
                verbose_name="closed",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="name",
            field=models.CharField(
                help_text="Name of the blog topic.", max_length=250, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="name_en",
            field=models.CharField(
                help_text="Name of the blog topic.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="name_uk",
            field=models.CharField(
                help_text="Name of the blog topic.",
                max_length=250,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="blogtopic",
            name="permissions",
            field=models.OneToOneField(
                blank=True,
                help_text="Blog post permissions.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.objectpermission",
                verbose_name="permissions",
            ),
        ),
    ]
