# Generated by Django 5.0.8 on 2025-02-05 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpost_content_alter_blogpost_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Creation date and time.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Update date and time.', verbose_name='updated at'),
        ),
    ]
