# Generated by Django 5.0.8 on 2025-02-17 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_blogpost_created_at_alter_blogpost_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="blogtopic",
            name="creator",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="blogtopic",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Creator of the blog post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blog_topics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
    ]
