name: CI-CD

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:

  backend:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Changing directory
        run: cd /home/urbanaut/backend

      - name: Updating code
        run: git pull origin master

      - name: Restarting supervisor task
        run: sudo supervisorctl restart backend