name: CI-CD

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:

  backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Mark Safe Directory for Git
        run: git config --global --add safe.directory /home/urbanaut/backend

      - name: Update Code
        run: git pull origin master
        working-directory: /home/urbanaut/backend

      - name: Restart Supervisor
        run: sudo /usr/bin/supervisorctl restart backend
