name: CI-CD

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:

  backend:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Code
        run: cp -r ./* /home/urbanaut/backend/

      - name: Restart Supervisor
        run: sudo /usr/bin/supervisorctl restart backend
