# Generated by Django 5.2.8 on 2026-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                help_text="Creation date and time.", verbose_name="created at"
            ),
        ),
    ]
