# Generated by Django 5.2.8 on 2026-04-27 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_alter_transaction_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="destination",
            field=models.JSONField(blank=True, null=True, verbose_name="destination"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Creation date and time.",
                verbose_name="created at",
            ),
        ),
    ]
